### ISSUE TITLE
batch-edit: adding new keywords causes deletion of existing keywords

### ISSUE THREAD

**Issue by pekingduck** [RhetTbull/osxphotos#1018]
osxphotos: 0.58.1, installed using pipx
OS: Ventura 13.2.1 (M1 Mac)

If I add some new keyword(s) to an image using `osxphotos batch-edit --keyword xxx`, all original/existing keywords (say "yyy" and "zzz") are deleted. Is this the intended behaviour?

Thanks

**Comment by RhetTbull** [comment]
This is by design but it may not be the best design. The `--keyword` option means "set keywords to this value" which as you noted overwrites existing keywords.  I did this because the `--title` and `--description` options overwrite the existing values and felt it was more consistent for keywords to do the same. I'm open to changing this behavior if it's not obvious.  Maybe add a `--overwrite-keywords` flag that, if not present, causes keywords to be appended.

In the meantime, you can add `--keyword "{keyword}"` (which is shown in the help text for batch-edit) which means "also add any existing keywords"

**Comment by RhetTbull** [comment]
@all-contributors please add @pekingduck for ideas

**Comment by RhetTbull** [comment]
@pekingduck I changed the `batch-edit` behavior in v0.58.2 so that it no longer overwrites the existing keywords and instead merges new keywords with the existing keywords. I also added a `--replace-keywords` option that causes existing keywords to be overwritten if specified.
