### ISSUE TITLE
Version 0.63.0: "Module object for pyimod02_importers is NULL!"

### ISSUE THREAD

**Issue by breun** [RhetTbull/osxphotos#1199]
**Describe the bug**

When trying to run the pre-built binary of osxphotos 0.63.0, I get an error saying "Module object for pyimod02_importers is NULL!".

**To Reproduce**
1. Download and expand https://github.com/RhetTbull/osxphotos/releases/download/v0.63.0/osxphotos_MacOS_exe_darwin_x86_64_v0.63.0.zip (linked on https://github.com/RhetTbull/osxphotos/releases/tag/v0.63.0).
2. Execute the `osxphotos` binary.

**Expected behavior**
I expected to see the `osxphotos` usage information, like I get with https://github.com/RhetTbull/osxphotos/releases/download/v0.62.3/osxphotos_MacOS_exe_darwin_arm64_v0.62.3.zip (linked on https://github.com/RhetTbull/osxphotos/releases/tag/v0.62.3).

**Desktop (please complete the following information):**
 - OS: macOS 13.5.1 arm64
 - osxphotos version: 0.63.0

**Comment by RhetTbull** [comment]
That's because that binary was built on x86 instead of arm64.  I normally do the release on an M1 machine but this time used an Intel Macbook.  I haven't figured out how to build a universal binary with pyinstaller.  I've built and uploaded a arm64 binary to the release page. Grab that one and give it a try. Honestly, I didn't think anyone actually used the pre-built binaries and I've been thinking about dumping these.  I use pipx for my own install because it's a lot easier to upgrade.

**Comment by breun** [comment]
I try to stay away from language-specific package managers (pip, pipx, npm, etc.), because I’d just end up having to use 30 different package managers to keep all my stuff up to date.

My main system-wide package manager is MacPorts, but sadly it doesn’t provide a port for `osxphotos` (yet) and although I maintain a couple of ports in MacPorts I don’t know enough about Python to create one for `osxphotos`. When MacPorts doesn’t provide something, I prefer following GitHub release feeds and manual updates over dealing with lots of different package managers.

I had expected the x86_64 binary to also work on arm64 via Rosetta, but apparently that doesn’t work. Thanks for uploading an arm64 binary!

**Comment by RhetTbull** [comment]
> My main system-wide package manager is MacPorts, 

I looked at create a port for osxphotos but frankly, it looks like more work than I have time for at the moment. And it would need to be updated (and follow the very detailed Macports PR guidelines) frequently as I release a new version of osxphotos a couple times a month, sometimes more frequently. That's why I like pipx.  I get it...I regularly use cargo, npm, and pipx for packages I use. I also use Mac ports and homebrew (because ports lacks so many packages that homebrew has). I tried for a while to standardize on Mac ports for my own Mac but many of the tools I need aren't available there.  It's a lot to keep up with. 

Perhaps if I have more time in the future I can look into adding support for Mac Ports and/or homebrew.  In the mean time I'll try to remember to add both x86 and arm binaries to the releases.

**Comment by breun** [comment]
If someone would create an initial port for MacPorts I wouldn’t mind keeping it up to date. I’d think that it should be possible to let a MacPorts port install this software without using another intermediate package manager (like `pipx` or `pip`), but I don’t know enough about the Python ecosystem to do that.

I’ll ask on the MacPorts dev mailinglist if someone would be willing to create a Portfile for `osxphotos`.
