### ISSUE TITLE
--query-eval photo.score.failure == 0 returns everything

### ISSUE THREAD

**Issue by frankrolf** [RhetTbull/osxphotos#1230]
**Before submitting a bug report, please ensure you are running the most recent version of osxphotos and that the bug is reproducible on the latest version**

```
osxphotos, version 0.63.5
Python 3.10.13 (main, Sep 18 2023, 17:23:48) [Clang 14.0.3 (clang-1403.0.22.14.1)]
macOS 13.5.2, arm64
```

**Describe the bug**
I am following the example found on https://www.reddit.com/r/osxphotos/comments/16hu79k/thank_you/ – my intent is adding “failed” photos to an album. However, it seems that this command will just match all the photos.

**To Reproduce**
1. What’s the full command line you used with osxphotos?
`osxphotos query --query-eval "{photo.score.failure == 0}"`

2. What was the error output?
All PIDs are output (~169K in my case)

**Expected behavior**
only PIDs with failure score == 0 are output

**Additional context**
I edited the example file `bad_photos.py` to return photos with failure score 0 (`failed_photos.py`, attached).
Running the script just returns ~220 PIDs, probably closer to the truth.

To add those to an album, I use this:
`osxphotos query --query-function failed_photos.py::failed_photos --add-to-album "my_failed_photos"`

This still does only add a handful of photos to the destination album, but I guess that’s something for the next bug report.

[failed_photos.py.zip](https://github.com/RhetTbull/osxphotos/files/12726541/failed_photos.py.zip)

**Comment by RhetTbull** [comment]
The example on reddit was wrong (I've edited the post  to fix it).  The actual query command should be:

`osxphotos query --query-eval "photo.score.failure == 0"  --not-shared`

The reddit example, `osxphotos query --query-eval "{photo.score.failure == 0}"`, evaluates `{photo.score.failure == 0}` which returns `True` or `False` inside a python set so it will always return a set with 1 item which resolves to `True` and thus every photo matches. When I wrote it I was thinking of an osxphotos template statement (which is included inside curly braces) but `--query-eval` takes a straight python statement.

As to why only some photos get added to albums, any photos in shared albums cannot be added to albums (unless first imported into the library as regular photos) which is why I've added the `--not-shared` flag. Shared photos don't get the same level of analysis as regular photos and I believe the scores will always be zero for shared photos.

Finally, you can get just the count of photos that match using:

`osxphotos query --query-eval "photo.score.failure == 0"  --not-shared --count`

**Comment by frankrolf** [comment]
Thank you very much for the response and thorough explanation!
