### ISSUE TITLE
import to iCloud Photos from image files? 

### ISSUE THREAD

**Issue by pcace** [RhetTbull/osxphotos#1244]
Hi there, 

i have just found osxphotos trying to find a way to upload images to icloud directly. From reading the documentation here i hope i understand correctly that i can sync a Photos library with the cloud, but cannot "just" send pictures to the cloud. 

Is this really not possible and if so would that be very complicated (or is there an other way?)

Thanks a lot for help!!

Cheers

**Comment by RhetTbull** [comment]
>  i understand correctly that i can sync a Photos library with the cloud, but cannot "just" send pictures to the cloud.

That's correct. The only way to send photos to iCloud directly is to add them via the iCloud web interface. You could log in to iCloud, select the Photos app, select the Library view then click the upload button (cloud with an "up arrow").  This is not a use case for osxphotos.

**Comment by pcace** [comment]
> > i understand correctly that i can sync a Photos library with the cloud, but cannot "just" send pictures to the cloud.
> 
> That's correct. The only way to send photos to iCloud directly is to add them via the iCloud web interface. You could log in to iCloud, select the Photos app, select the Library view then click the upload button (cloud with an "up arrow"). This is not a use case for osxphotos.

Hi, thanks a lot for your reply! And i understand that this seems to be not possible :/ 
i have a couple houndred thousand pictures i want to add to icloud. but its more then my little macbooks ssd can store :/ so i guess i try to make some kind of an uploader using curl... if thats even possible..

**Comment by RhetTbull** [comment]
> so i guess i try to make some kind of an uploader using curl... if thats even possible..

I have no idea if that's possible. However, you could take a look at [iCloud Photos Downloader](https://github.com/icloud-photos-downloader/icloud_photos_downloader) which might offer some clues for interacting with the iCloud API.

There are other alternatives. Switch your Photos library on the Mac to "Optimize Mac Storage" in `Photos > Settings > iCloud` so that Photos will delete originals off the Mac to save space (once they're uploaded to iCloud). You could then import them into batches in Photos, wait for Photos to sync to iCloud and then it will automatically delete the local copy in the Photos library (not the original you imported from). Be sure that `Photos > Settings > General > Copy Items to the Photos Library` is checked. 

You could do this manually by dragging a folder at a time of photos into Photos, wait for it to sync, then drag the next folder. Or you could use `osxphotos import` command to import them automatically. This also allows you set metadata upon import, parse the date from the filename, etc. You could do the same thing, import a folder at a time, let it sync, import the next folder. The biggest disadvantage to using `osxphotos import` is that currently it imports one photo at a time so you won't be able to see all those photos in one import group under the "Imports" tab.

Another alternative is this (and this is what I would do in your situation):  On your Mac, ensure that `Photos > Settings > iCloud > Optimize Mac Storage` is checked so originals aren't downloaded.  Create a second user account on the Mac. Login to the new account and sign in to your iCloud account. Hold down Option while starting Photos and create a new library -- create this library on an external drive that has enough space for all your photos. Designate this new library as the system library (`Photos > Settings > General > Use as System Photo Library`) Copy all the photos to this library and wait until iCloud syncs. Will take a very long time for 100ks of photos.

You will need to keep this second user account logged in to the Mac until this process finishes but you can switch to your primary account using Fast User Switching and keep working while the second account syncs in the background.

**Comment by pcace** [comment]
> > so i guess i try to make some kind of an uploader using curl... if thats even possible..
> 
> I have no idea if that's possible. However, you could take a look at [iCloud Photos Downloader](https://github.com/icloud-photos-downloader/icloud_photos_downloader) which might offer some clues for interacting with the iCloud API.
> 
> There are other alternatives. Switch your Photos library on the Mac to "Optimize Mac Storage" in `Photos > Settings > iCloud` so that Photos will delete originals off the Mac to save space (once they're uploaded to iCloud). You could then import them into batches in Photos, wait for Photos to sync to iCloud and then it will automatically delete the local copy in the Photos library (not the original you imported from). Be sure that `Photos > Settings > General > Copy Items to the Photos Library` is checked.
> 
> You could do this manually by dragging a folder at a time of photos into Photos, wait for it to sync, then drag the next folder. Or you could use `osxphotos import` command to import them automatically. This also allows you set metadata upon import, parse the date from the filename, etc. You could do the same thing, import a folder at a time, let it sync, import the next folder. The biggest disadvantage to using `osxphotos import` is that currently it imports one photo at a time so you won't be able to see all those photos in one import group under the "Imports" tab.
> 
> Another alternative is this (and this is what I would do in your situation): On your Mac, ensure that `Photos > Settings > iCloud > Optimize Mac Storage` is checked so originals aren't downloaded. Create a second user account on the Mac. Login to the new account and sign in to your iCloud account. Hold down Option while starting Photos and create a new library -- create this library on an external drive that has enough space for all your photos. Designate this new library as the system library (`Photos > Settings > General > Use as System Photo Library`) Copy all the photos to this library and wait until iCloud syncs. Will take a very long time for 100ks of photos.
> 
> You will need to keep this second user account logged in to the Mac until this process finishes but you can switch to your primary account using Fast User Switching and keep working while the second account syncs in the background.

Hi thanks again for your help! I am currently trying to figure out how to upload via curl... if that does not work, i will get closer to your suggested methods ;) 

currently i am trying this: 

```
  curl 'https://p154-uploadimagews.icloud.com/upload?filename=img.jpeg&dsid=185869684&lastModDate=1696870960236&timezoneOffset=-120' \
  -H 'authority: p154-uploadimagews.icloud.com' \
  -H 'accept: */*' \
  -H 'accept-language: de-DE,de;q=0.9' \
  -H 'content-type: image/jpeg' \
  -H 'cookie: myCookie.... \
  -H 'origin: https://www.icloud.com' \
  -H 'referer: https://www.icloud.com/' \
  -H 'sec-ch-ua: "Google Chrome";v="117", "Not;A=Brand";v="8", "Chromium";v="117"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36' \
--data "@/Users/user/Desktop/img.jpeg" \
  --compressed

```
wich returns:
`
{"errors":[{"errorCode":"EXIF_ERROR"}],"requestUUID":"78484fd1-c0e5-4edd-83ee-7c4705ba995f"}`

so at least there is something happening ;) but EXIF_ERROR? hmm there is nothing to find to that error. that will be hard to figure out^^


cheers

**Comment by pcace** [comment]
if anyone ever finds this... this is how i upload images:

```
#!/bin/bash

# Setze den Startpfad
START_DIRECTORY="/Volumes/Data/img"

# Log-Datei erstellen
LOG_FILE="log_file.log"

# Funktion zum Protokollieren
log() {
  local message="$1"
  echo "$(date '+%Y-%m-%d %H:%M:%S') - $message" >> "$LOG_FILE"
}

# Funktion zur Berechnung des ETA
calculate_eta() {
  local total_files="$1"
  local processed_files="$2"
  local start_time="$3"
  
  local current_time=$(date +%s)
  local elapsed_time=$((current_time - start_time))
  local avg_time_per_file=$((elapsed_time / processed_files))
  local remaining_files=$((total_files - processed_files))
  local eta_seconds=$((avg_time_per_file * remaining_files))
  
  local eta_hours=$((eta_seconds / 3600))
  local eta_minutes=$((eta_seconds % 3600 / 60))
  local eta_seconds=$((eta_seconds % 60))
  
  echo "$eta_hours:$eta_minutes:$eta_seconds"
}
# Zähle die Anzahl der JPEG- und JPG-Dateien im Ordner und seinen Unterordnern
file_count=$(find "$START_DIRECTORY" -type f -name "*.jpg" -o -name "*.jpeg" | wc -l)
processed=0

# Schleife durch alle JPEG- und JPG-Dateien im Ordner und seinen Unterordnern
find "$START_DIRECTORY" -type f -name "*.jpg" -o -name "*.jpeg" | while read -r file; do
  # Extrahiere den Dateinamen ohne Pfad
  echo "Verarbeite Datei: $file"

  # Lade die Datei mit curl hoch
  if curl 'https://p154-uploadimagews.icloud.com/upload?filename=img.jpeg&dsid=185869684&lastModDate=1696870960236&timezoneOffset=-120' \
    -H 'authority: p154-uploadimagews.icloud.com' \
    -H 'accept: */*' \
    -H 'accept-language: de-DE,de;q=0.9' \
    -H 'content-type: image/jpeg' \
    -H 'origin: https://www.icloud.com' \
    -H 'cookie: LOGINCOOKIE' \
    -H 'referer: https://www.icloud.com/' \
    -H 'sec-ch-ua: "Google Chrome";v="117", "Not;A=Brand";v="8", "Chromium";v="117"' \
    -H 'sec-ch-ua-mobile: ?0' \
    -H 'sec-ch-ua-platform: "macOS"' \
    -H 'sec-fetch-dest: empty' \
    -H 'sec-fetch-mode: cors' \
    -H 'sec-fetch-site: same-site' \
    -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36' \
    --data-binary "@$file" \
    --compressed; then
    log "Erfolgreich hochgeladen: $file"
  else
    log "Fehler beim Hochladen: $file"
  fi

  # Erhöhe den Fortschrittszähler
  ((processed++))

  # Berechne und gib den Fortschritt sowie die geschätzte Ankunftszeit (ETA) aus
  eta=$(calculate_eta "$file_count" "$processed" "$start_time")
  echo "Fortschritt: $processed von $file_count Dateien verarbeitet (ETA: $eta)"
  
  # Falls es die erste Datei ist, speichere den Startzeitpunkt
  [[ "$processed" -eq 1 ]] && start_time="$(date +%s)"
done

echo "Hochladen abgeschlossen."
```

**Comment by RhetTbull** [comment]
Thanks -- nice work. It might be a useful feature for osxphotos to be able to upload to iCloud in the future
