### ISSUE TITLE
self built executable throws error

### ISSUE THREAD

**Issue by britiscurious** [RhetTbull/osxphotos#128]
I have set a a dev environment for osxphotos based on python 3.8.2.
Everything is working if I invoke cli.py
But if I build an executable with help of make_cli_exe.sh and try to run it I get the following error:

[84939] Error loading Python lib '/var/folders/jw/2t6k1dy963xd344v_xh9fr8w0000gn/T/_MEIF7TZXn/Python': dlopen: dlopen(/var/folders/jw/2t6k1dy963xd344v_xh9fr8w0000gn/T/_MEIF7TZXn/Python, 10): no suitable image found.  Did find:
	/var/folders/jw/2t6k1dy963xd344v_xh9fr8w0000gn/T/_MEIF7TZXn/Python: code signature invalid for '/var/folders/jw/2t6k1dy963xd344v_xh9fr8w0000gn/T/_MEIF7TZXn/Python'

**Comment by RhetTbull** [comment]
How did you install python? (For example, anaconda, home brew, directly from python.org)?

Are you using a virtual environment and if so, how did you create it?

**Comment by britiscurious** [comment]
Direct download from python.org. No virtual environment. (At least not intentionally set up by me.)

**Comment by RhetTbull** [comment]
OK, I've not tested with that version (I use Anaconda).  I do recommend you learn about [virtual environments](https://docs.python.org/3/tutorial/venv.html) because it'll save you lot of headache as you do more python development.  In summary, virtual environments create a separate copy of python and any needed libraries/packages for each project to avoid conflicts, for example, if one project requires a different version of a python package than another project.  

I'm traveling and don't have access to my Mac so it'll be a week or two before I can look at this specific issue.  Ideally, the exe should build on the official python distro from python.org.  My primary intent with the single-file exe is to make it easy for people who don't have python installed to use.  It uses [pyinstaller](https://www.pyinstaller.org/) to bundle the python executable and all needed code and packages into a single self-extracting zip.  Because of this it can fairly slow to execute as the zip has to unzip each time you run it.  I will try to debug this though when I get back home.

Since you already have a python development environment, I recommend you install with `python3 setup.py install` which will create the `osxphotos` command line tool.  You can also install with [pipx](https://github.com/pipxproject/pipx)

**Comment by britiscurious** [comment]
Gave it a try with a virtual environment. But result remains the same.
Nevertheless, please close the issue. `python3 setup.py install` works fine.
I did not recognize that it also creates an executable.
Thought it was only for retrieving required dependencies.

**Comment by RhetTbull** [comment]
I've verified that as of 0.42.29 with Python.org 3.9.5, pyinstaller builds without error. The requirements.txt and dev_requirements.txt are now streamlined and use latest package versions which seems to have solved the problem.
