### ISSUE TITLE
database disk image is malformed

### ISSUE THREAD

**Issue by jdblank** [RhetTbull/osxphotos#1333]
Hi thanks for a great app. I am just getting started trying my first export and get the following error:

database disk image is malformed

Attached is crash log.

Thanks,

Josh
[osxphotos_crash.log](https://github.com/RhetTbull/osxphotos/files/13693839/osxphotos_crash.log)

**Comment by RhetTbull** [comment]
The error is occurring while trying to read one of the databases in your Photos library (`~/Pictures/Photos Library.photoslibrary/search/psi.sqlite`) which contains metadata about the photos. This file appears to be corrupt. 

I would try to [repair the Photos library](https://support.apple.com/en-us/HT204967#:~:text=1%20Hold%20down%20the%20Option%20and%20Command%20keys,Repair%20to%20start%20the%20repair%20process.%20See%20More) and then try the export. This is a Photos error not one caused by osxphotos.  This database is not strictly needed to do an export (it contains labels / categories assigned by Photos to the images, not information about the images that you have added) but as currently written, osxphotos cannot do the export because of the error. I'll add code to catch this and continue the export if the search database cannot be read.  This is the first time in thousands of exports I've seen this.

**Comment by jdblank** [comment]
OK thanks. I restarted photos and now it seems to be working.

**Comment by RhetTbull** [comment]
Glad it's working. Let me know if you run into any other issues.
