### ISSUE TITLE
Document the ability to open iOS/iPhone Photos libraries.

### ISSUE THREAD

**Issue by axelkar** [RhetTbull/osxphotos#1477]
You've already implemented it in #791 so why not document it?

For me, `ifuse` is plenty fast. Maybe you could use [pymobiledevice3](https://pypi.org/project/pymobiledevice3/) to get an easy UX.

Do you have a command for exporting and then deleting photos? What about one that deletes them from the filesystem too?

**Comment by RhetTbull** [comment]
This ability is documented in the docs for the [sync command](https://rhettbull.github.io/osxphotos/cli.html#osxphotos-sync) as that's the only command that can easily make use of an iPhone Photos database. It's not possible, as far as I know, to use the export command from an iPhone as the photo paths are different and osxphotos doesn't account for this.

pymobiledevice3 looks interesting but it's licensed under GPL which isn't compatible with osxphotos so it's not something I can incorporate in osxphotos.

If you have a good workflow for using osxphotos with an iPhone, you're welcome to write it up and I can include it in the docs. I suggest starting with documenting it in our [discussions](https://github.com/RhetTbull/osxphotos/discussions) pages.

> Do you have a command for exporting and then deleting photos? What about one that deletes them from the filesystem too?

osxphotos cannot delete photos from Photos. What I suggest is to use the `--add-to-album` feature to add the exported photos to an album in Photos and then you can delete them from there. (If you use `Command+Delete` on photos in an album, they will be sent to the Recently Deleted folder. If you use only `Delete`, they are only removed from the album but not the library).

**Comment by axelkar** [comment]
Can Photos on macOS or iOS fix a corrupted database by itself? Will all metadata get lost if osxphotos or anything corrupts or deletes the database? Will all photos get orphaned? How about orphaned photos or photos missing from the filesystem but which are still in the database? Have you tested that?

**Comment by RhetTbull** [comment]
> Can Photos on macOS or iOS fix a corrupted database by itself? 

Yes. On macOS, see [repair Photos library](https://support.apple.com/en-us/118221). No idea about iOS since that's a black box.

> Will all metadata get lost if osxphotos or anything corrupts or deletes the database? 

osxphotos doesn't write to database normally so querying or exporting with osxphotos cannot corrupt the database. The only osxphotos tool that writes directly to the database is `osxphotos timewarp` and this warns the user to make a backup then prompts the user to continue. `osxphotos import` and `osxphotos sync` can make changes but these are all done through the public Photos AppleScript interface so any corruption would be the responsibility of Photos.

I have seen Photos corrupt a database but I've never seen metadata lost. Usually running the Photos library repair tool is sufficient for fixing the database.

> Will all photos get orphaned? How about orphaned photos or photos missing from the filesystem but which are still in the database? Have you tested that?

I don't know what would cause photos to get orphaned. osxphotos does have a `osxphotos orphans` tool that finds orphaned files (in the filesystem but not referenced in the database) and can export these with `osxphotos orphans --export`.
