### ISSUE TITLE
iOS 12.5.7 (16H81) Photos schema

### ISSUE THREAD

**Issue by axelkar** [RhetTbull/osxphotos#1483]
**Is your feature request related to a problem? Please describe.**
OSXPhotos can't load `PhotoData/Photos.sqlite` from an iPad running iOS 12.5.7 (16H81).

```
2024-03-31 21:42:37,632 - root - WARNING - photosdb_utils.py - 119 - Unknown model version: 12310
Traceback (most recent call last)
...
in _process_database5
...
OperationalError: no such table: ZASSET
```

**Describe the solution you'd like**
Support the schema :)

**Describe alternatives you've considered**
None

**Additional context**

Here's the schema:
https://gist.github.com/axelkar/29bc127ba6d8347768c733636fe5481d

**Comment by axelkar** [comment]
I think this might work for `_DB_TABLE_NAMES`:
```py
{
        "ASSET": "ZGENERICASSET",
        "KEYWORD_JOIN": "Z_1KEYWORDS.Z_34KEYWORDS",
        "ALBUM_JOIN": "Z_23ASSETS.Z_30ASSETS",
        "ALBUM_SORT_ORDER": "Z_23ASSETS.Z_FOK_30ASSETS",
        "IMPORT_FOK": "ZGENERICASSET.Z_FOK_IMPORTSESSION",
        "DEPTH_STATE": "ZGENERICASSET.ZDEPTHSTATES",
        "UTI_ORIGINAL": "ZINTERNALRESOURCE.ZUNIFORMTYPEIDENTIFIER",
        "ASSET_ALBUM_JOIN": "Z_23ASSETS.Z_23ALBUMS",
        "ASSET_ALBUM_TABLE": "Z_23ASSETS",
        "HDR_TYPE": "ZCUSTOMRENDEREDVALUE",
        "DETECTED_FACE_PERSON_FK": "ZDETECTEDFACE.ZPERSON",
        "DETECTED_FACE_ASSET_FK": "ZDETECTEDFACE.ZASSET",
}
```

**Comment by RhetTbull** [comment]
Hi @axelkar Thanks for your work on the PR to add support for this. This is a big change and it includes changes I am not able to test because I don't have access to a test library from this iOS version. I will have to think about whether or not to incorporate this PR. iOS is not a primary target for osxphotos -- the fact that it can read iOS databases is a "bonus" because the schemas are nearly identical. I'm not sure it is worth the maintenance burden to make big changes to the code to support one particular version of iOS which is long outdated. 

If your changes work for you then you could of course continue to use your own version to export from this version of iOS.

I'll spend some more time studying the changes in the PR and thinking about whether or not to incorporate this.

**Comment by axelkar** [comment]
I completely understand that it's hard to develop for and maintain such an old schema with limited access. Feel free to close the PR and this issue whenever you wish.
