### ISSUE TITLE
Exporting photos, errored out, entire photo library deleted...

### ISSUE THREAD

**Issue by heisian** [RhetTbull/osxphotos#1594]
Latest verseion installed via `pipx`

**Describe the bug**
Ran `osxphotos` to perform an export of a backed-up photo libarary, after getting through a certain number of photos (see error output below), the program stopped and I've discovered that my photo library is pretty much nuked.

I don't know if is possible that `osxphotos` could have wiped the photos library on its own. I do have multiple backups of my library but would like to know why this has happened.

One thing that may be out of the ordinary is that to allow Photos to load a network-stored library, I have a virtual disk/image (dmg) stored on my network share, and inside of that I place my *.photoslibrary archives. This workaround allows me to access libraries stored on my NAS.

**To Reproduce**
1. What' the full command line you used with osxphotos?
`osxphotos export /Volumes/Backup/iCloud\ Photos/Exports-Tim --update --exiftool --library /Volumes/macOS\ Photo\ Image/Tim.photoslibrary --directory "{created.year}/{created.mm}"`
3. What was the error output?
```
Error exporting photo (D7A0D990-CAD6-4305-A50F-0D6585479FE3: 8A5250A6-F6E9-4AEE-862C-5EF8CE2DCD68.jpeg) as 8A5250A6-F6E9-4AEE-862C-5EF8CE2DCD68.jpeg: RetryError[<Future at 0x1166125a0 state=finished raised OperationalError>]
Error exporting photo (5770CC5A-DFC1-4EFF-A62B-9566368427A2: IMG_0155.JPG) as IMG_0155.JPG: RetryError[<Future at 0x10fe34590 state=finished raised OperationalError>]
Error exporting photo (F30505AF-E757-4974-B9FD-FEEDF6971906: 23401E83-7DC2-42C8-B2FF-9A638E421B47.jpeg) as 23401E83-7DC2-42C8-B2FF-9A638E421B47.jpeg: RetryError[<Future at 0x1165eefc0 state=finished raised OperationalError>]
Exporting 4872 photos ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processed: 4872 photos, exported: 210, updated: 0, skipped: 126, updated EXIF data: 210, missing: 0, error: 4635
Elapsed time: 0:13:35
Something went wrong and osxphotos encountered an error:
RetryError[<Future at 0x10fe34a10 state=finished raised OperationalError>]
Crash log written to '/Volumes/Backup/osxphotos_crash.log'
Please file a bug report at https://github.com/RhetTbull/osxphotos/issues with the crash log attached.
```
**Desktop (please complete the following information):**
 - OS: Ventura 13.6.7
 - osxphotos version (`osxphotos --version`)
```
 - osxphotos, version 0.68.2
Python 3.12.4 (main, Jun  6 2024, 18:26:44) [Clang 15.0.0 (clang-1500.1.0.2.5)]
macOS 13.6.7, x86_64
```

**Additional context**
My photo library that was about 60 GB is now showing up as 128 MB after osxphotos errored out. Luckily I have ZFS snapshots and can restore the old library otherwise I'd be screwed.

To be clear I am running `osxphotos` from my Macbook against a photo library and export destination that are both on my server (SMB shares). I didn't expect the tool to almost completely erase my photo library, though.

**Comment by heisian** [comment]
Contents of crash log:
```
osxphotos crash log
Created: 2024-06-22 12:07:29.008693
osxphotos version: 0.68.2
Platform: macOS-13.6.7-x86_64-i386-64bit
Python version: 3.12.4 (main, Jun  6 2024, 18:26:44) [Clang 15.0.0 (clang-1500.1.0.2.5)]
sys.argv: ['/Users/heisian/.local/bin/osxphotos', 'export', '/Volumes/Backup/iCloud Photos/Exports-Tim', '--update', '--exiftool', '--library', '/Volumes/macOS Photo Image/Tim.photoslibrary', '--directory', '{created.year}/{created.mm}']
CRASH_DATA:
locals: {'dest': '/Volumes/Backup/iCloud Photos/Exports-Tim', 'db': '/Volumes/macOS Photo Image/Tim.photoslibrary', 'add_exported_to_album': None, 'add_missing_to_album': None, 'add_skipped_to_album': None, 'added_after': None, 'added_before': None, 'added_in_last': None, 'album': (), 'album_keyword': False, 'alt_db': None, 'alt_copy': False, 'append': False, 'fix_orientation': False, 'beta': False, 'burst': False, 'checkpoint': None, 'cleanup': False, 'cloudasset': False, 'config_only': False, 'convert_to_jpeg': False, 'crash_after': None, 'current_name': False, 'deleted': False, 'deleted_only': False, 'description': (), 'description_template': None, 'directory': '{created.year}/{created.mm}', 'download_missing': False, 'dry_run': False, 'duplicate': False, 'edited': False, 'edited_suffix': None, 'exif': (), 'exiftool': True, 'exiftool_merge_keywords': False, 'exiftool_merge_persons': False, 'exiftool_option': (), 'exiftool_path': None, 'export_as_hardlink': False, 'export_by_date': False, 'exportdb': None, 'external_edit': False, 'favorite': False, 'favorite_rating': False, 'filename_template': None, 'finder_tag_keywords': False, 'finder_tag_template': (), 'folder': (), 'force_update': False, 'from_date': None, 'from_time': None, 'has_comment': False, 'has_likes': False, 'has_raw': False, 'hdr': False, 'hidden': False, 'ignore_case': False, 'ignore_date_modified': False, 'ignore_exportdb': False, 'ignore_signature': False, 'in_album': False, 'incloud': False, 'is_reference': False, 'jpeg_ext': None, 'jpeg_quality': None, 'keep': (), 'keyword': (), 'keyword_template': (), 'label': (), 'limit': None, 'live': False, 'load_config': None, 'location': False, 'max_size': None, 'min_size': None, 'missing': False, 'name': (), 'no_comment': False, 'no_description': False, 'no_exportdb': False, 'no_keyword': False, 'no_likes': False, 'no_location': False, 'no_place': False, 'no_progress': False, 'no_title': False, 'not_burst': False, 'not_cloudasset': False, 'not_edited': False, 'not_favorite': False, 'not_hdr': False, 'not_hidden': False, 'not_in_album': False, 'not_incloud': False, 'not_live': False, 'not_missing': False, 'not_panorama': False, 'not_portrait': False, 'not_reference': False, 'not_screenshot': False, 'not_selfie': False, 'not_shared': False, 'not_slow_mo': False, 'not_time_lapse': False, 'only_movies': False, 'only_new': False, 'only_photos': False, 'original_suffix': None, 'overwrite': False, 'panorama': False, 'person': (), 'person_keyword': False, 'place': (), 'portrait': False, 'post_command': (), 'post_command_error': None, 'post_function': (), 'preview': False, 'preview_if_missing': False, 'preview_suffix': None, 'print_template': (), 'query_eval': (), 'query_function': (), 'ramdb': False, 'regex': (), 'replace_keywords': False, 'report': None, 'retry': None, 'save_config': None, 'screenshot': False, 'selfie': False, 'shared': False, 'export_aae': False, 'sidecar': (), 'sidecar_drop_ext': False, 'sidecar_template': (), 'skip_bursts': False, 'skip_edited': False, 'skip_live': False, 'skip_original_if_edited': False, 'skip_raw': False, 'skip_uuid': (), 'skip_uuid_from_file': None, 'slow_mo': False, 'strip': False, 'theme': None, 'time_lapse': False, 'timestamp': False, 'title': (), 'tmpdir': None, 'to_date': None, 'to_time': None, 'touch_file': False, 'update': True, 'update_errors': False, 'use_photokit': False, 'use_photos_export': False, 'uti': None, 'uuid': (), 'uuid_from_file': None, 'verbose_flag': 0, 'xattr_template': (), 'year': (), 'syndicated': False, 'not_syndicated': False, 'saved_to_library': False, 'not_saved_to_library': False, 'shared_moment': False, 'not_shared_moment': False, 'shared_library': False, 'not_shared_library': False, 'selected': False, 'ctx': <click.core.Context object at 0x10d348b00>, 'cli_obj': <osxphotos.cli.cli.CLI_Obj object at 0x110915970>}
osxphotos version: 0.68.2
Error: [Errno dbfile /Volumes/macOS Photo Image/Tim.photoslibrary/database/photos.db does not exist] /Volumes/macOS Photo Image/Tim.photoslibrary/database/photos.db
Traceback (most recent call last):
  File "/Users/heisian/.local/pipx/venvs/osxphotos/lib/python3.12/site-packages/osxphotos/crash_reporter.py", line 79, in wrapped
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/heisian/.local/pipx/venvs/osxphotos/lib/python3.12/site-packages/osxphotos/cli/export.py", line 1115, in export
    return_code = export_cli(**locals())
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/heisian/.local/pipx/venvs/osxphotos/lib/python3.12/site-packages/osxphotos/cli/export.py", line 1866, in export_cli
    photosdb = osxphotos.PhotosDB(
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/heisian/.local/pipx/venvs/osxphotos/lib/python3.12/site-packages/osxphotos/photosdb/photosdb.py", line 342, in __init__
    raise FileNotFoundError(f"dbfile {dbfile} does not exist", dbfile)
FileNotFoundError: [Errno dbfile /Volumes/macOS Photo Image/Tim.photoslibrary/database/photos.db does not exist] /Volumes/macOS Photo Image/Tim.photoslibrary/database/photos.db
```

**Comment by RhetTbull** [comment]
Very sorry to hear about this but glad you had a backup. There's nothing `osxphotos export` does that should damage or modify the Photos library in any way. Here's what the export command does:

- Attempt to open the `Photos Library.photoslibrary/database/Photos.sqlite` in read-only mode to load the metadata about the library.
- If this fails because the database is exclusively locked, it copies the database to a temporary directory and opens the temporary copy.
- Once the database is loaded, the export begins and at that point, osxphotos does not read any data from the library except for checking that the expected path to a photo asset exists when it needs to copy the asset out of the library. Assets are copied out of the library using the native macOS NSFileManager functions unless `--alt-copy` is specified in which case `shutil.copy()` is used. In no case does osxphotos every call a function which moves, modifies, or deletes any files from the Photos library.
- If the `--add-exported-to-album` or one of the other `--add-X-to-album` options is used, osxphotos interacts with Photos using the Apple-provided AppleScript interface to create the album and copy the asset to the album. 
- Options such as `--exiftool` that modify the exported file first copy the file to a temporary directory, modify the temporary copy, then copy the the modified file to the final destination. In no case is any destructive operation applied to a file in the actual Photos library.

The only osxphotos command that actually modifies files directly in the Photos library is `osxphotos timewarp` which needs to directly modify the database to adjust timezones. The user is warned before this operation begins that they should make a backup of the library.  Even in this case, the only thing modified by osxphotos is the `Photos.sqlite` file.

> The original crash log from the run above was overwritten by the new crash log below

I will open a new issue to add a date stamp to the crash log to prevent this from happening. See #1595

> One thing that may be out of the ordinary is that to allow Photos to load a network-stored library, I have a virtual disk/image (dmg) stored on my network share, and inside of that I place my *.photoslibrary archives. This workaround allows me to access libraries stored on my NAS.

Photos really does not like to operate on anything but the internal drive or a very fast directly connected external drive. This is because the underlying sqlite database used by Photos does not work well over network drives.  Given this is a very non-standard setup I can't predict what Photos would do. 

It should not matter whether Photos is running or not. If you use the `--add-X-to-album` then osxphotos will start Photos to use the AppleScript interface. I run osxphotos daily with Photos running without issue.

> To be clear I am running `osxphotos` from my Macbook against a photo library and export destination that are both on my server (SMB shares)

OSXPhotos also uses a sqlite database to store the export state in the export directory (`.osxphotos_export.db`) unless you have used `--exportdb` to specify an alternate location. If you are exporting to an SMB drive you should use `--ramdb` to store the database in RAM and/or use `--exportdb` to specify an alternate location. The `RetryErrror` is likely because something happened to the SMB connection during export which cause the export database to be corrupt or unavailable. I do have an open issue (#1419) to detect SMB volumes automatically and force the use of `--ramdb` which loads the database into RAM for the duration of the export the writes it to the export directory when done.

My best guess is that something happened with SMB volume that caused data corruption but I don't think this is related to osxphotos. Between my daily backups and the testing I do with each osxphotos release, I've run the tool many thousands of time and have never seen anything like this. (I run over 1,000 tests for every release and have never seen anything like this). I'm particularly suspicious of the DMG mounted over an SMB share.  If I can get some additional data that indicates osxphotos is at fault I will certainly look into it. My primary use for osxphotos is to backup my personal Photos library so I've spent a lot of time trying to ensure that maximum data is preserved and that no harm comes to my library.

**Comment by RhetTbull** [comment]
I don't have an SMB volume for testing but I did create a DMG volume, copied a test Photos library there, then did an export using the same options you used and used my [dirsnapshot](https://github.com/RhetTbull/dirsnapshot) tool to see what files changed. As expected, the only changes were modification of the sqlite write ahead log .shm file which is modified even when the database is opened in read-only mode. 

```
❯ dirsnap --diff before.db after.db
diff '/Volumes/TestPhotos' 2024-06-22T16:10:08.669983 (Snapshot created at 2024-06-22T16:10:08.669983) vs 2024-06-22T16:11:00.942146 (Snapshot created at 2024-06-22T16:11:00.942146)
Added:

Removed:

Modified:
    /Volumes/TestPhotos/Test-13.0.0.photoslibrary/database/Photos.sqlite-shm
    /Volumes/TestPhotos/Test-13.0.0.photoslibrary/database/search/psi.sqlite-shm
❯ 
```

I also ran `osxphotos snap` and `osxphotos diff` on the test library in the DMG before/after the export and as expected, there are no differences in the `Photos.sqlite` database.

```
❯ osxphotos diff --library /Volumes/TestPhotos/Test-13.0.0.photoslibrary
❯ 
```

**Comment by heisian** [comment]
Trying this procedure again using `osxphotos` installed directly on my server, rather than having my Macbook attempt to export over network shares.

**Comment by heisian** [comment]
Alright I'm pretty sure the issue is me trying to run `osxphotos` over the network, where both the photos library is on a network share and the export directory is on a network share. It runs significantly faster with it installed on the server itself, and seems like it will complete in 4 minutes vs the 13 hours estimated in my previous runs. I'm going to close this bug report...

**Comment by heisian** [comment]
> I don't have an SMB volume for testing but I did create a DMG volume, copied a test Photos library there, then did an export using the same options you used and used my [dirsnapshot](https://github.com/RhetTbull/dirsnapshot) tool to see what files changed. As expected, the only changes were modification of the sqlite write ahead log .shm file which is modified even when the database is opened in read-only mode.
> 
> ```
> ❯ dirsnap --diff before.db after.db
> diff '/Volumes/TestPhotos' 2024-06-22T16:10:08.669983 (Snapshot created at 2024-06-22T16:10:08.669983) vs 2024-06-22T16:11:00.942146 (Snapshot created at 2024-06-22T16:11:00.942146)
> Added:
> 
> Removed:
> 
> Modified:
>     /Volumes/TestPhotos/Test-13.0.0.photoslibrary/database/Photos.sqlite-shm
>     /Volumes/TestPhotos/Test-13.0.0.photoslibrary/database/search/psi.sqlite-shm
> ❯ 
> ```
> 
> I also ran `osxphotos snap` and `osxphotos diff` on the test library in the DMG before/after the export and as expected, there are no differences in the `Photos.sqlite` database.
> 
> ```
> ❯ osxphotos diff --library /Volumes/TestPhotos/Test-13.0.0.photoslibrary
> ❯ 
> ```

Thank you for verifying. There must have been some unknown interaction with the Photos app, maybe the .dmg mounting, maybe an issue with network share stability (I'm just throwing things out there..), but it's working excellent now that I'm using the CLI from the server.

Thank you!!

**Comment by heisian** [comment]
> I will open a new issue to add a date stamp to the crash log to prevent this from happening. See https://github.com/RhetTbull/osxphotos/issues/1595

Sweet! Thank you!

**Comment by RhetTbull** [comment]
To satisfy my curiosity I created a test environment that replicates your scenario as best as I could. I mounted an external volume attached to another Mac as an SMB share then created a DMG on the network share in which I placed a test library. I snapshotted the Photos library before and after as above and did an export using your configuration. It was very slow but worked as expected. As above the only change to the Photos library was that the write-ahead log had been modified due to reading from the Photos database.

```
dirsnap --diff before.db after.db
diff '/Volumes/TestPhotos' 2024-06-23T22:13:18.273077 (Snapshot created at 2024-06-23T22:13:18.273077) vs 2024-06-23T22:18:53.519967 (Snapshot created at 2024-06-23T22:18:53.519967)
Added:

Removed:

Modified:
    /Volumes/TestPhotos/.DS_Store
    /Volumes/TestPhotos/Test-13.0.0.photoslibrary/database/Photos.sqlite-shm
    /Volumes/TestPhotos/Test-13.0.0.photoslibrary/database/search/psi.sqlite-shm
```
