### ISSUE TITLE
exportdb --history | Performance enhancement

### ISSUE THREAD

**Issue by oPromessa** [RhetTbull/osxphotos#1765]
**Is your feature request related to a problem? Please describe.**
`osxphotos exportdb .osxphotos_export.db --history FILE_PATH` is  slow operation.

**Describe the solution you'd like**
I've added the following indexes to the exported which greatly  speeds things up.
```sql
create index idx_history_filepath_id ON history (filepath_id);
create index idx_history_path_uuid ON history_path (uuid);
```

**Describe alternatives you've considered**
Manually adding the indexes to .osxphotos_export.db 

**Additional context**
Will try to produce a PR by increasing export DB version number to 10.1 and adding a migrate function similar to `_migrate_9_1_to_10_0`. Any other places to change, maybe add some tests?

Hopefully it does not slow down the export function. Will test it.

https://github.com/RhetTbull/osxphotos/blob/c90beeffaabcfdd0344c56c09b093b518190db0c/osxphotos/export_db.py#L43

https://github.com/RhetTbull/osxphotos/blob/c90beeffaabcfdd0344c56c09b093b518190db0c/osxphotos/export_db.py#L1089

**Comment by RhetTbull** [comment]
Yes, your proposed solution should be all that's required: bump the DB version number, add a migration check and add a migration function that simply creates the indexes. Please use all caps for the SQL to maintain convention of the other code in `export_db.py` and use `CREATE INDEX IF NOT EXISTS...` so that a migration on an already migrated database doesn't cause errors. (This shouldn't happen but if someone manually changed the version number I'd want the migration to still work).
