### ISSUE TITLE
Feature : support other OS

### ISSUE THREAD

**Issue by gdelab** [RhetTbull/osxphotos#25]
This library could prove quite useful when transferring a library from Mac to Windows or Linux, for instance to organize the pictures, keep their metadata (including albums), etc. 

Is it something that could be feasible, or does this code use Apple proprietary code or something like that ?

**Comment by RhetTbull** [comment]
It would be feasible to port the code to run on non-Mac platforms but would take some work.  The core of the module would run fine on Windows/Linux as it uses sqlite3 to read the Photos database and extract metadata.  However, there is some Mac-specific code in the helper functions (e.g. find the default Photos library, etc.) but this code wouldn't be needed on another platform as you would have to provide full path to the database.  The export code is also Mac-specific so that would need to be re-written. 

I've thought about making this cross-platform but my assumption is that most people using it would be doing so on MacOS.  Porting it would require adding a bunch of if/else statements to separate the MacOS specific code increasing the complexity of the code a bit as well as making testing more difficult. 

Is this something you have a use-case for?  If there's enough interest, I may consider a port.

**Comment by gdelab** [comment]
Hey ! 
Sorry I left this personal project aside for a while.
I've changed computer from Mac to Windows, so I'd like to transfer my photo library as well. 
I had spent a lot of time organizing everything in albums, and marking faces. I would like to keep at least my albums, and I thought your project could help me do that, by creating directories in windows for each album, and put symbolic links to the pictures in it. (the real picture file would remain in the directory by date or something I guess). I figured your code could help me a lot to parse the Mac OS library.

I haven't figured out how to keep the faces, but Windows Photos seems quite good at re-finding and grouping them.

**Comment by RhetTbull** [comment]
@gdelab it would take some work but this is possible. I’ve not worked on this project much lately due to being too busy but will look into separating the Mac-specific code out when I have time. If you have access to a Mac, it would be relatively easy to write a small script to do what you want (e.g. symlink photos into albums) — for example onto an external drive that you could then copy to your Windows machine. The face names could be stored in the EXIF data of the photo so Windows could access it.

**Comment by RhetTbull** [comment]
As work on osxphotos has progressed I've had to add more MacOS-specific code.  Porting this to run on other platforms would take significant work and I don't have any interest in doing this.  I'll happily consider a PR but do not plan on implementing this myself.

**Comment by RhetTbull** [comment]
Thanks to @dvdkon this is now implemented in v0.60.0
