### ISSUE TITLE
Support Media type as a template for directory name

### ISSUE THREAD

**Issue by narensankar0529** [RhetTbull/osxphotos#255]
Would it be possible to add media time as a template for naming directories - for example this would allow photos and videos and screenshots to be exported to separate directories at the top level

for example 

photos/2020/December
screenshots/2019/February
slow-mo/2016/January

**Comment by RhetTbull** [comment]
Great suggestion -- thanks.  This would be fairly easy to implement with the current templating system. However, given the current design, the user wouldn't be able to specify the name of the media type -- e.g. if "foto" if they wanted to localize the names.

**Comment by narensankar0529** [comment]
It might be acceptable to use whatever the Photos Database says the media type is by default and not have any media type overrides.

**Comment by RhetTbull** [comment]
This turned out to be a lot easier than I thought! I've got an alpha version implemented.  I decided to add two new template fields: `media_type` and `special_type`.  `media_type` is either `photo` or `video`.  `special_type` is `panorama`, `slow_mo`, etc. and defaults to `photo` or `video` accordingly if no special type.  I decided to override the DEFAULT value in the template system to allow the user to customize how the type is represented.  E.g. you can do this:

`--directory "{media_type,photo=fotos;video=vidéos}"`

and all photos will be exported to "fotos" and all videos exported to "vidéos"

I need at add tests but should be able to get this pushed out this weekend.

**Comment by RhetTbull** [comment]
Photos defines media types like this:

<img width="214" alt="Screen Shot 2020-11-07 at 10 35 39 AM" src="https://user-images.githubusercontent.com/41546558/98449015-16f9c780-20e5-11eb-96ba-19174b557c8f.png">

So I plan to implement `special_type` (or maybe rename `media_type` and `special_type` as I've implemented to match Photos) with the same categories.  Does that fit your use case?  The only issue I see is perhaps Live Photos as some people leave live photo on by default and might not consider these to be "special".

**Comment by RhetTbull** [comment]
Some photos can belong to more one than one media type (e.g. selfie and burst".  Need to figure out how to handle these.  Could make this a multi-value media type but would be simpler to make it a single value.

**Comment by narensankar0529** [comment]
I think Live Photos should be a special_type - because the most common reason you may want to separate out while exporting is because your gallery software might not handle Live Pictures. So having them separate allows you to script further operations depending on how you want them to be displayed.

The rest is ideal as you have represented them with the special_type

For photos with multiple media types - I would suggest that pick only a single value. For example you gave selfie and burst, the value would be selfie - since for most people the more important one would be selfie

At a high level the main reason to have this functionality is just because a lot of gallery software do not handle all the nuances of types of media that Photos support and having items separated out allows scripting to either flatten the media - for example with Live pictures or Portraits, or to represent them separately in the gallery while displaying. 

So what you have so far to me works great. It will completely simplify my export process from 4 separate exports to one, and reduce having to keep 4 databases to just one global one speeding up the export and sync.

**Comment by RhetTbull** [comment]
I've implemented this feature in [v0.36.10](https://github.com/RhetTbull/osxphotos/releases/tag/v0.36.10).  I decided to use `{media_type}` to represent the special media types in order to be consistent with Photos.  I implemented a precedence order as you suggested with `live_photo` and `burst` lower on the precedence.  I also added `{photo_or_video}` template field that resolves to `photo` or `video` accordingly.  Also, both these new fields support customization or localization by overriding the default field, e.g. `"{media_type,video=vidéo;time_lapse=vidéo_accélérée}"`

**Comment by narensankar0529** [comment]
Great! This works very well. Tried it out now. Thanks a lot for making this happen.
