### ISSUE TITLE
Add --query-eval for query & export

### ISSUE THREAD

**Issue by RhetTbull** [RhetTbull/osxphotos#280]
Example:

`osxphotos export --query-eval "[p for p in photos if p.score.overall > 0.6]"`

This would filter files by evaluating a single python statement.  These could be chained with multiple --query-eval options.  Execute query-eval after all other query options have been executed.  `photos` would be defined in local scope and represent list of PhotoInfo objects from previous query.  Must return a list of PhotoInfo objects.

**Comment by ubrandes** [comment]
This would be another great feature for this great tool. I've already wondered if it wouldn't be useful to create more Template Substitutions, such as `{favorite?IS_FAV,NO_FAV}` or `{overall_score}`. But the above suggestion would be an elegant way of offering the same flexibility without creating more features.
As syntax for `osxphotos export --query-eval` related to the above example (and many others) I'd suggest 

`osxphotos export --query-eval "score.overall > 0.6"`

so that people can tinker with the Package Interface without having to tinker with Python specifics.

**Comment by RhetTbull** [comment]
Thanks for the feedback.  A `--query-eval` feature serves a different purpose than the template substitutions as it's used to filter the results and the template substitution is used to name the resulting output file or folder (or keyword, etc).  I like the simplified syntax you propose for this.  As for a `{favorite}` template, I have an open issue (#289) to add additional template fields and will add `{favorite}` to the list.

**Comment by ubrandes** [comment]
Thank you for your swift reply, Rhet.

I thought I could emulate {favorite} in the meantime by creating a python program to use the package instead of the command line. But I’ve never worked with Python, and I’m stuck already at the very first hurdle, importing osxphotos:

UB@Mac ~ % python3
Python 3.9.2 …
>>> import osxphotos
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'osxphotos'
>>> Ctrl-D
UB@Mac ~ % pipx list
venvs are in /Users/UB/.local/pipx/venvs
apps are exposed on your $PATH at /Users/UB/.local/bin
   package osxphotos 0.41.8, Python 3.9.2
    - osxphotos


What can I do to help Python find the osxphotos module?!  Respectively, where in the file system is the osxphotos module supposed to be located?


I’ve installed osxphotos following your instructions on my otherwise standard Mac on BigSur, however I had to reinstall the Xcode CLI tools because pip failed to build package xattr , and I had to run pipx ensurepath to ensure proper paths:

UB@Mac ~ % brew install pipx
clang: error: invalid version number in 'MACOSX_DEPLOYMENT_TARGET=11'
UB@Mac ~ % sudo rm -rf /Library/Developer/CommandLineTools
UB@Mac ~ % sudo xcode-select --install
UB@Mac ~ % pipx install osxphotos 
installed package osxphotos 0.41.8
Note: '/Users/UB/.local/bin' is not on your PATH environment variable.
UB@Mac ~ % osxphotos -v
zsh: command not found: osxphotos
UB@Mac ~ % pipx ensurepath
UB@Mac ~ % osxphotos -v
osxphotos, version 0.41.8
UB@Mac ~ % osxphotos list
/Users/UB/Pictures/Fotos-Mediathek…

So everything seems good on my end, but how is Python3 instructed to find the osxphotos module?

I get the above error message regardless which of the 3 Python versions on my Mac I try:
/usr/bin/python3 (Python 3.8.2)
/usr/local/bin/python3 (Python 3.9.2, installed today)
/usr/bin/python (Python 2.7.16)

Am I to expect many more of such hurdles with the package, as a newbie to Python?  Then it seems I’ll have to wait for {favorite} and --query-eval ;-( 

Thank you, kind regards
Ulf Brandes

**Comment by RhetTbull** [comment]
pipx installs an executable version of osxphotos in a virtual environment so your python won't be able to find it. The whole point of pipx is to install executable python packages in a way that they each run in their own environment separate from your system python.  Read more about virtual environments [here](https://docs.python.org/3/tutorial/venv.html).  

I recommend you install python from [python.org](https://www.python.org/downloads/mac-osx/), create a virtual environment then `python3 -m pip install osxphotos`.  Then look at the example programs in the github repo to get you started.

Once you get that far, let me know if you have any other questions!

**Comment by ubrandes** [comment]
Thank you for your kind support, Rhet.  Actually I’ve found out that when I start Python3 from folder ~/.local/pipx/venvs/osxphotos/lib/python3.9/site-packages then I can import osxphotos within Python3 without further ado.  And I’ve had fun now checking out all the automatically generated photo labels and scores in OSXPhotos… interesting!

I had installed osxphotos from pipx, and now it works.  So this is good for now, I guess, thank you!

**Comment by RhetTbull** [comment]
I've prototyped this feature but the format will have to a be a bit different to work with a wider variety of query cases.  Basically, the user will need to supply `CRITERIA` in the following list comprehension:

```python
photos = [photo for photo in photos if CRITERIA]
```

This would allow you do things like this:
`--query-eval "photo.favorite"`
`--query-eval "'Tree' in photo.labels"`
`--query-eval "photo.score.overall > 0.6"`

**Comment by RhetTbull** [comment]
Implemented in [v0.41.10](https://github.com/RhetTbull/osxphotos/releases/tag/v0.41.10)

**Comment by ubrandes** [comment]
> 've already wondered if it wouldn't be useful to create more Template Substitutions, such as `{favorite?IS_FAV,NO_FAV}` or `{overall_score}`. But the above suggestion would be an elegant way of offering the same flexibility without creating more features.

Ahhm... I realized my assumption was wrong that `--quer-eval` was an elegant substitute for Template Substitutions. For instance, to have Templates in `--keyword`, `--filename` or `--directory` we'd need multiple runs of different `--query-eval`expressions, which may lead to unexpected results particularly with `--cleanpu`, and takes a long time with a large library. 

Hence, it would be great to have `{favorite}` and actually also `{place.name}`, in order to implement `--keyword` and `--filename` templates such as in `osxphotos export . --filename "{original_name[#,_edited,]}{hdr?~,}{edited?#,}{favorite?!,}" --keyword-template "{place.name}" 

Or maybe, how's this as a more flexible substitution syntax, to facilitate a wider variety of cases: A `=`as in `--filename "{original_name}**{=photo.favorite?!,}**"` or in `--keyword-template "**{=place.name}**"` could indicate that what follows the `=`is actually an expression similar to the query expressions in `--query-eval` — what do you think?

**Comment by RhetTbull** [comment]
The `{place.name}` template is currently implemented as are several other place related fields.  What you propose would be an elegant solution to allow access to arbitrary metadata.  I'll take a look at the template grammar and see how hard it would be to add something like this.

**Comment by RhetTbull** [comment]
Reference new issue #417
