### ISSUE TITLE
Getting directory named _ during export

### ISSUE THREAD

**Issue by wormiedk** [RhetTbull/osxphotos#285]
I am exporting photos using this command:
./osxphotos export --folder "2020" --update --cleanup --original-suffix "_original" --edited-suffix "" --exiftool --directory '{folder_album}' --album-keyword --filename '{created.date} {created.hour}.{created.min}.{created.sec}' /Volumes/Plextra/OSXPhotos

After the export I end up with a folder called _ which contains duplicates of photos under 2020. Is there some way I can see why I get these photos? 
It might be related to burst photos somehow as all the photos have (1), (2), ..., (8) in their name e.g:
2016-03-18 16.41.55_original (1).JPG

**Comment by RhetTbull** [comment]
@wormiedk "_" is the default value for any template that evaluates to a null/empty value.  In your case, you must have some photos that aren't in an album so when you use `--directory '{folder_album}' ` the template evaluates to the album name and folder path if there is one otherwise it resolves to "_".  You can override this by providing a default value to the template, for example:
`--directory '{folder_album,Photos with no album}'` in which case those photos will go into a folder called `Photos with no album`.  The default value goes after a comma following the template keyword.

Regarding the (1), (2), etc. that happens if a photo has an identical name to another and is placed in the same output folder.  In your case because you're using a template for `--filename` based on time, you have multiple photos taken in the same second (so yes, these could be bursts).

**Comment by wormiedk** [comment]
Yes but the strange thing is that a folder cannot contain photos only albums which then contain photos so where are the photos in the _ folder coming from? I do have photos which are not in an album but by definition they are not in a folder?!?

**Comment by RhetTbull** [comment]
From the command line help text:

```
Folder path + album photo is contained in. e.g.  'Folder/Subfolder/Album' or just 'Album' if no enclosing folder
```

If photos are not in any album this template resolves to none and thus uses the default value.
