### ISSUE TITLE
pformat is not defined

### ISSUE THREAD

**Issue by kylebarron** [RhetTbull/osxphotos#30]
Looks like you're using `pformat` here
https://github.com/RhetTbull/osxphotos/blob/098159466e298825f540ebb6cfd8ba667c88a478/osxphotos/photoinfo.py#L91
but you never imported it
https://github.com/RhetTbull/osxphotos/blob/098159466e298825f540ebb6cfd8ba667c88a478/osxphotos/photoinfo.py#L7-L19

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-76-bf626b80307d> in <module>
      1 for p in photos:
----> 2     p.json()

~/local/anaconda3/envs/create-database/lib/python3.7/site-packages/osxphotos/photoinfo.py in json(self)
    489             "albums": self.albums,
    490             "persons": self.persons,
--> 491             "path": self.path,
    492             "ismissing": self.ismissing,
    493             "hasadjustments": self.hasadjustments,

~/local/anaconda3/envs/create-database/lib/python3.7/site-packages/osxphotos/photoinfo.py in path(self)
     89             else:
     90                 photopath = None
---> 91                 logging.debug(f"WARNING: masterFingerprint null {pformat(self._info)}")
     92 
     93             # TODO: fix the logic for isMissing

NameError: name 'pformat' is not defined
```

**Comment by kylebarron** [comment]
Also, for this photo, it looks like `path` is None, but `p.ismissing` is `False`

**Comment by RhetTbull** [comment]
Thanks! I've fixed the missing import.  I've never seen a null path if ismissing is False though I suppose it's possible--I had to make a lot of assumptions about the data used to compute path. It's also possible there's a bug in the code for computing path.  What version of MacOS & Photos are you running?   The code below should dump info about any other photos with a missing path.  If you don't mind running this, does it find any other photos?

```python
import osxphotos
from pprint import pformat

photosdb = osxphotos.PhotosDB()

photos = photosdb.photos()
for photo in photos:
    if photo.path is None and not photo.ismissing:
        print(f"Missing path: {pformat(photo._info)}")
```

**Comment by kylebarron** [comment]
That found 329 results. I exported them to a JSON file to make transferring easier, but apparently Github doesn't allow you to upload files with a JSON extension, so here's a JSON file with a .txt extension:
[export.txt](https://github.com/RhetTbull/osxphotos/files/4000611/export.txt)

I ran this:
```py
import osxphotos
import json

photosdb = osxphotos.PhotosDB()

photos = photosdb.photos()
photos = [x for x in photos if x.path is None and not x.ismissing]
l = []
for p in photos:
    d = p._info.copy()
    if not isinstance(d['lastmodifieddate'], str):
        d['lastmodifieddate'] = d['lastmodifieddate'].isoformat()
    if not isinstance(d['imageDate'], str):
        d['imageDate'] = d['imageDate'].isoformat()
    l.append(d)

with open('export.json', 'w') as f:
    json.dump(l, f)
```

**Comment by RhetTbull** [comment]
Thanks for additional data.  I'll take a closer look later today.  On quick peek it appears these photos might either be in iCloud (and not on the local disk) or in a shared iCloud album -- in either case, ismissing should be 1 (not null) and path should be None.  It's possible they're in a shared album and on the disk but the code doesn't yet deal with these photos which are stored differently than photos in the main library--it's on my to-do list.  

Do you know if these are photos you expected to be in the main library and downloaded from iCloud?  You might be able to find an example photo by searching by photo.original_filename (originalFilename in your JSON file).

 Photos <= 4.0 had a field called "ismissing" that made this easy to figure out--Photos 5 doesn't have that database field and instead, I've got to compute this based on other data--likely there's a bug in that logic that misses this edge case.  I'll do some more debugging.

**Comment by kylebarron** [comment]
It's definitely possible that they're in iCloud and not on local disk. I recently got a new computer and Photos still hasn't fully synced. I haven't looked manually  at the filenames to see if I expect them to exist

**Comment by RhetTbull** [comment]
If photos weren't yet synched from the cloud, _info["remoteavailability"] should have been set to 0 but in your example data, it's null meaning the code to set it never got run.  It would be easier to debug with a copy of your database (~/Pictures/Photos Library.photoslibrary/database/Photos.sqlite) -- if you're willing to share that, you can email me the file or a cloud share link to rturnbull + git @ gmail.com  -- either way, I'll keep digging into this.  The code was working pretty good for Photos4 but Apple completely re-wrote Photos5 in 10.15 and I had to reverse engineer the database all over again.  I'm guessing there's some edge case I haven't run into yet.  It's also interesting that masterFingerprint is null in your examples but I've never seen this in my testing. 

This is the code that should have set localavailability/remoteavailabilty/isMissing but isn't doing so in your case.  

https://github.com/RhetTbull/osxphotos/blob/2917bb78ff6127241ba10ce7e1466748cad11b04/osxphotos/photosdb.py#L945-L965

**Comment by kylebarron** [comment]
I emailed you a Firefox Send link

**Comment by RhetTbull** [comment]
Got the link & the database -- thanks.  I'm able to isolate those 329 results but still working on figuring out why those are different.  I believe those photos are in a shared iCloud library (which aren't currently supported by osxphotos and should have been filtered out).  Can you take a look in your ~Pictures/Photos Library.photoslibrary/ folder and see if these files are present:

resources/cloudsharing/data/282257456/998369B7-DB21-4315-BC31-B1CD210C46CE/FA861DBA-D226-4358-AFC3-4342FEBE7E0A.jpeg
resources/cloudsharing/data/282257456/998369B7-DB21-4315-BC31-B1CD210C46CE/A9FF5523-1D77-48D0-B948-15C36EF97C5A.jpeg

They might end with "_poster.jpeg" instead of just ".jpeg"

Also, can you confirm that these files are *not* present (e.g. ismissing = 1)
resources/cloudsharing/data/282257456/A37372D7-5DA6-4641-A9E4-F5E4110752C9/E82A659B-3073-4A5F-8058-CC0BF57924A3.JPG
resources/cloudsharing/data/282257456/A37372D7-5DA6-4641-A9E4-F5E4110752C9/DFA27F19-3DDD-4D23-8DBD-0E8268D8743C.JPG

Of course, it's possible the latter two were not present when you sent me the database but now are present because they were subsequently synched from iCloud.

**Comment by kylebarron** [comment]
The first two are present exactly as you've described, i.e. these exist:
```
resources/cloudsharing/data/282257456/998369B7-DB21-4315-BC31-B1CD210C46CE/FA861DBA-D226-4358-AFC3-4342FEBE7E0A.jpeg
resources/cloudsharing/data/282257456/998369B7-DB21-4315-BC31-B1CD210C46CE/A9FF5523-1D77-48D0-B948-15C36EF97C5A.jpeg
```
And the latter two don't exist.

The former two are both in a shared album.

**Comment by RhetTbull** [comment]
I think I've figured this out.  A true fix will mean implementing support for shared albums which I'm now working on but might take a little time.  In the meantime, I've made a temporary fix which should ignore those photos.  The current code will check to see if photo is in a shared album and if so, ignore it when processing the database.  You won't be able to see those photos with osxphotos but you also shouldn't get the errors due to missing path or ismissing=None.

**Comment by RhetTbull** [comment]
I've added support for shared photos/albums in the latest version on github.  v0.18.0 adds the following properties to PhotosDB:
albums_shared
albums_shared_as_dict

and adds the following property to PhotoInfo
shared

The 329 photos in your database with path=None now correctly show up as shared photos and ismissing appears to be set correctly.

**Comment by kylebarron** [comment]
Awesome! I really love the library.
