### ISSUE TITLE
Sanitize Folder-names

### ISSUE THREAD

**Issue by richardmayer** [RhetTbull/osxphotos#316]
Hello,

I'm using the commandline version of osxphotos to export an backup my library.
Thanks for all the efforts! Great work!

One thing is bugging me:
I have Albums with slashes in the Album-Names and I'm using the template --directory "{folder_album}" to export my photos.
This way, there are slashes in the folder-names. This is no problem, when using and viewing the folders in Mac OS.
But when I'm trying to Upload my Backup via Transmit or rsync, these folder make problems, because slashes are not allowed in regular linux/unix-systems.
Is there any way to sanitize the Folder-names to linux-format right when exporting them via command-line?

Best regards

Richard

**Comment by RhetTbull** [comment]
@richardmayer I'll take a look at this. I do sanitize all the folder names but I use a "MacOS" sanitize algorithm.  I had not considered your use case of backing up to a non-Mac filesystem.  I'll take a look at the code and see what I can figure out.

**Comment by RhetTbull** [comment]
@richardmayer What error message are you getting from Transmit or your backup app?  Here's what osxphotos actually does to sanitize filenames:
- If there's a "/" in the folder name, it replaces the "/" with  ":" which is allowed on both MacOS and linux (but not Windows). 
- In Finder, MacOS displays folder names with a ":" as having a "/" even though the folder name on disk really has ":"

For example:
<img width="558" alt="Screen Shot 2021-01-01 at 9 12 42 AM" src="https://user-images.githubusercontent.com/41546558/103443281-483cd280-4c12-11eb-8d7c-d03fb361f864.png">

<img width="595" alt="Screen Shot 2021-01-01 at 9 10 58 AM" src="https://user-images.githubusercontent.com/41546558/103443287-4c68f000-4c12-11eb-8b58-c8971100f053.png">

It may be that Transmit is interpreting the ":" as a "/" because it knows Finder does this.  

It would be possible to add an option to allow you to specify a custom path separator for album names.

**Comment by richardmayer** [comment]
Hello, 
thanks for your quick reply.
Maybe I was on the wrong track with this being a problem with all linux target systems.
I tried with a linux-target-system via sftp rsync and transmit and the slashes were correctly transferred as : .

The original problem of my backup occured with a WebDAV-Share (GMX Cloud).
So maybe this was just a problem with this particular hoster (Error Message in Transmit:
The server sent this message:
bad request
).
They don't seem to accept the :-signs in the Folder-Name.
So I guess that osxphotos can't do anything about this problem.
Of course a custom path separator might be  a nice "deluxe" feature for the future.

Thanks for your time!

Richard

**Comment by RhetTbull** [comment]
I think I have a simple and elegant solution for this.  I've modified the template syntax to allow for an optional "directory separator"  (DIR_SEP) that will be used, if specified, whenever a folder name would be generated with a ":" or a "/".  

New template syntax would be:

`{DELIM+TEMPLATE_FIELD(PATH_SEP)[DIR_SEP]?VALUE_IF_TRUE,DEFAULT}`

So in your case you could do this:

`--directory "{folder_album[-]}"` 

and every "/" in album name would be replaced by new directory separator "-"

Will take some time to implement this and write tests but I've already prototyped it and seems to work.

**Comment by RhetTbull** [comment]
Like DELIM, PATH_SEP and DEFAULT, the new DIR_SEP would be optional so if you did this:

`--directory "{folder_album}"`

the behavior of osxphotos would match what it does now ("/" converted to ":")

**Comment by richardmayer** [comment]
Hello,

yes, that sounds like a great solution.
I'd be very happy to see it implemented in a future release, and I'm sure, I'm not the only guy!

Best regards

Richard

**Comment by RhetTbull** [comment]
Thinking about this some more -- I think a more generalized solution would be better.  Instead of just specifying a directory separator, the template system could allow arbitrary single character substitutions.  For example:

`--directory "{folder_album[/,-]}"` would substitute "-" for "/".  This could support multiple substitutions or even deleting characters in form:
`--directory "{folder_album[/,-|:,-|;,]}"`

This last example is read: 
- replace "/" with "-"
- replace ":" with "-"
- replace ";" with nothing (delete ";")

Open to any suggestions on format -- I'm running out characters that don't already meaning in the template system. Need a separate delimiter between characters and between pairs of substitutions.

**Comment by RhetTbull** [comment]
Generalized text replacement feature added to templates in [v0.39.4](https://github.com/RhetTbull/osxphotos/releases/tag/v0.39.4).  It takes as specified in previous comment:

--directory "{folder_album[/,-]}" would substitute "-" for "/". This could support multiple substitutions or even deleting characters in form:
--directory "{folder_album[/,-|:,-|;,]}"

This last example is read:

    replace "/" with "-"
    replace ":" with "-"
    replace ";" with nothing (delete ";")
