### ISSUE TITLE
download-missing gives error

### ISSUE THREAD

**Issue by narensankar0529** [RhetTbull/osxphotos#351]
This is the only error in the log -

Error exporting photo IMG_8955.HEIC (EC3ED783-0411-43DF-98C8-55C75E156FC7.heic) as photo_191128_EC3ED783-0411-43DF-98C8-55C75E156FC7.HEIC: 'NoneType' object is not iterable

Running second time works since the file is already downloaded somehow.

**Comment by RhetTbull** [comment]
Were you using --use-photokit with --download-missing or just --download-missing?

I've seen this a couple of times where there's an intermittent error when trying to download with --download-missing but it works the second time.  If I can figure out where in the code the actual error is happening I'll add a loop to catch the error and automatically retry

**Comment by narensankar0529** [comment]
No I was not using --use-photokit. Just plain --download-missing

Yes - running a second time goes through fine without errors

**Comment by RhetTbull** [comment]
I added an automatic retry to [v0.39.19](https://github.com/RhetTbull/osxphotos/releases/tag/v0.39.19).  This issue is caused by flakiness of Photos' AppleScript engine (which Apple seems to have abandoned long ago).  If there's an error during export with --download -missing, the code will now automatically retry up to 3 times.  Let me know if you are still seeing errors.
