### ISSUE TITLE
Exporting with exiftool issue with --update

### ISSUE THREAD

**Issue by persimmonsoft** [RhetTbull/osxphotos#369]
I am trying to export all my Photos to allow for hosting on my Synology and I have run into the following issue:

The command I am using is:

```
osxphotos export --cleanup --export-by-date --update --overwrite \
	--exiftool --exiftool-option '-m' --exiftool-option '--ext AVI' \
	--skip-original-if-edited --skip-live --skip-bursts --skip-raw \
	--db "$src" "$dst"
```

I get many of the following errors:
`Error exporting photo (4FE63355-7D12-4190-83BF-E813742AE27A: IMGP0034.JPG) as IMGP0034.JPG: Expecting value: line 1 column 1 (char 0)`

I saw these during an update as well after adding locations to many photos.

I have tried this export to the SMB share as well as to an external drive and receive the same errors.
When that error occurs, those photos are removed as part of the cleanup.

Is this something I am doing wrong or is it a bug?

**Comment by RhetTbull** [comment]
Definitely a bug but not sure what's triggering it.  The error message itself looks like it's generated from the json package during json decoding so that gives me some ideas where to look.  Certain details about the photo are cached in the export database for use with --update and some of those are stored as json so that's a likely place this is occurring.  I'll see what I can figure out.

**Comment by persimmonsoft** [comment]
Let me know if there is anything I can do or provide to help.

Thanks for a great tool.

**Comment by RhetTbull** [comment]
I was able to replicate this. I'm fairly certain the culprit is "--exiftool-option '-ext AVI'" Not sure why yet but if I remove that, export works as expected.

What are you trying to do with that option?  Try without it and let me know if it works.

**Comment by persimmonsoft** [comment]
Looks like that worked. I was using that AVI setting to remove a bunch of these warnings:

```
  [##################------------------]   52%  00:09:31exiftool error for file /Volumes/home/Drive/Moments/iCloudPhotos/2007/02/21/MVI_1452.AVI: Error: Writing of AVI files is not yet supported - /Volumes/home/Drive/Moments/iCloudPhotos/2007/02/21/MVI_1452.AVI
Error exporting photo (5A9E549A-80FB-4CE7-978F-3E291132057A: MVI_1452.AVI) as /Volumes/home/Drive/Moments/iCloudPhotos/2007/02/21/MVI_1452.AVI: Error: Writing of AVI files is not yet supported - /Volumes/home/Drive/Moments/iCloudPhotos/2007/02/21/MVI_1452.AVI
```

Looks like I will have to wait for AVI support in exiftool to get rid of those then. Unless you have a suggestion.

**Comment by RhetTbull** [comment]
I figured out the problem but not sure how to solve it. I'll ask over on the [exiftool forum](https://exiftool.org/forum/index.php) to see if anyone there knows.   I'm using exiftool in a subprocess with -stay_open to execute the commands (prevents having to re-spawn a new process for each image) and in this mode, exiftool is interpreting `--ext AVI` as a tag command:

```txt
exiftool -stay_open True -@ - -common_args -n -P -G
--ext AVI
/Users/rhet/Downloads/test.jpg
-execute
Invalid TAG name: "ext AVI"
```

**Comment by RhetTbull** [comment]
I think I found and fixed the problem in [v0.40.11](https://github.com/RhetTbull/osxphotos/releases/tag/v0.40.11).  With -stay_open, exiftool expects each part of an option to be passed separately.  Thus "--ext AVI" needs to be passed as:
```
--ext\n
AVI\n
```

instead of:
```
--ext AVI\n
```

I now check for multi-part options and send them to exiftool separately

Let me know if you still encounter issues.

**Comment by RhetTbull** [comment]
Turns out there were 2 issues: the way I was passing the multi-part options as noted above and not checking for valid json when reading from exiftool (which 0.40.12 fixes).  If you use `--ext AVI` on an AVI file, exiftool acts as if the file doesn't actually exist and produces error: `No file with specified extension`.

**Comment by persimmonsoft** [comment]
Thank you, I'll try the new version soon.

BTW, I noticed that if I pass in
`--exiftool-option "-q"`
to quiet exiftool while running, it never finishes the first photo and stalls.

There may not be anything you can do about it, but I thought you might want to know. (It was another attempt at quieting the AVI errors.)

**Comment by RhetTbull** [comment]
>BTW, I noticed that if I pass in
--exiftool-option "-q"
to quiet exiftool while running, it never finishes the first photo and stalls.

I don't think I can easily fix this.  osxphotos runs a single exiftool process and communicates with it via pipe (much faster than spinning up a new process for each photo).  In this mode, exiftool outputs `"{ready}"` after each command is executed and osxphotos looks for this to know when the command is done.  With `-q`, exiftool outputs nothing after running a command so osxphotos hangs, looking for the "{ready}" sentinel which never arrives. I could probably engineer around this but not worth the effort.

**Comment by persimmonsoft** [comment]
That makes sense. It is not a big deal to see a few errors, I was just trying to clean it up.
Thanks again for the great tool
