### ISSUE TITLE
No photos.db in my version of Photos Library

### ISSUE THREAD

**Issue by cfiske** [RhetTbull/osxphotos#390]
I'm on Catalina 10.15.7, Photos Version 5.0 (161.0.120). When I tried to run osxphotos it complained that there is no photos.db in my Photos library. I looked and my database folder only has the Photos.sqlite database. I tried specifying `--db Pictures/Photos\ Library.photoslibrary/database/Photos.sqlite` but then I get
`sqlite3.OperationalError: no such table: LiGlobals`. This is on Python 3.8, osxphotos 0.40.19 (installed via pip).

I poked around and I discovered that using `get_model_version()` on the sqlite file works:
```
>>> from osxphotos.photosdb.photosdb_utils import get_model_version
>>> get_model_version('Pictures/Photos Library.photoslibrary/database/Photos.sqlite');
13703
>>>
```
I looked around and the various queries to the Photos.sqlite database in the photosdb module appear to work, but the code doesn't get that far when photos.db is not present.

**Comment by RhetTbull** [comment]
Interesting--in all my testing on MacOS from 10.12 to 10.16 I've never seen this.  I just a did a test on 10.15.7 and created a new Photos library.  There was a photos.db created but then I tried deleting it and opening Photos and it worked fine.  I'm guessing Photos creates this so that older versions of Photos will realize it's the wrong version and refuse to open the database.  

In Catalina, Photos switched from photos.db but the osxphotos code, which I originally wrote on 10.12, expected photos.db to be present so I've left that bit of the code and then switch to Photos.sqlite if the code detects it's a Photos 5+ database.  It'll take a little work to re-work the version check but I'll fix it so the code switches to Photos.sqlite if no photos.db is located.

**Comment by RhetTbull** [comment]
In the mean time, try this: create a new Photos library by holding down Option while opening Photos. Then copy the photos.db from this new library to your existing library's database folder and try osxphotos.  (This assumes Photos creates the photos.db in the new library)

**Comment by neilpa** [comment]
You could also copy the [`photos.db`](https://github.com/RhetTbull/osxphotos/blob/master/tests/Test-10.15.7.photoslibrary/database/photos.db?raw=true) from one of the test libraries in this repo

**Comment by cfiske** [comment]
Yep, creating a new album and copying did the trick. Thanks!

In thinking back on this, I think what happened was that I restored the library to my new laptop from a rather crude incremental backup drive. In looking at one point I noticed duplicate sets of database files, some which hadn't been modified in years (since iPhoto -> Photos conversion, or older to newer Photos db version?), and decided I didn't need those since Photos worked fine without them. That'll teach me. :)
