### ISSUE TITLE
Remove dot from beginning of filename

### ISSUE THREAD

**Issue by sirnacnud** [RhetTbull/osxphotos#416]
I have some videos in my Photos library that the filename starts with a `.`, such as `.recorded-` or `.filtered-`. They do get exported correctly, but aren't visible in Finder by default, which caused me to think they didn't get exported. I believe the videos are from Snapchat, and I guess they used this naming scheme with the dot when you saved videos from the app.

Would it be possible to have an option to remove this dot from the beginning of the filename or is it already possible to fix this?

**Comment by RhetTbull** [comment]
Does the filename always start with the same text? If so you could use the template system to rename the files and replace the text:

`--filename "{original_name[.recorded,recorded|.filtered,filtered]}"`

This used the original filename for export (the default) but replace any occurrence of ".recorded" with "recorded" and any instance of ".filtered" with "filtered". 

Alternatively you could add a prefix to every filename using something like this:

`--filename "prefix_{original_name}"`

This would add "prefix_" to *every* file exported. So your filename would be something like "prefix_.filtered_image_name.jpeg" Of course, replace "prefix_" with whatever prefix you want to use.

**Comment by sirnacnud** [comment]
Yes they always start with the same text. Using the template system to rename the files worked. Thank you for the help!

**Comment by RhetTbull** [comment]
@sirnacnud In [v0.42.00](https://github.com/RhetTbull/osxphotos/releases/tag/v0.42.00) I've added conditional expressions to the osxphotos template language which drives the template engine so you should be able to  use the following to rename just the files that begin with ".":

`--filename "{original_name startswith .?prefix-{original_name},{original_name}}"`

This is read as "if original_name starts with . then add 'prefix-' to the original name otherwise use the original name when exporting.

**Comment by RhetTbull** [comment]
I also just realized that you could do this more simply with:

`--filename "{original_name[.,]}"`

which would remove any "." in the filename (with exception of the suffix).
