### ISSUE TITLE
Incremental export of albums

### ISSUE THREAD

**Issue by Rott-Apple** [RhetTbull/osxphotos#465]
If I export an album, then add some more photos to the album (without any editing), and re-export the album incrementally, I would expect only the newly added photos to be exported. OSXPhotos doesn't seem to do this. The query I'm using is: 
osxphotos export /Desktop/ExportPhotos --album name --update --only-new. This is with macOS Big Sur.

The desired behavior would be that only the photos that have either been added to the album or edited since the previous export should be exported.

**Comment by RhetTbull** [comment]
To get the desired behavior, you don't need `--only-new`. I just did the following test:

`osxphotos export /Desktop/ExportPhotos --album name --update`

Added photos to album `name`

`osxphotos export /Desktop/ExportPhotos --album name --update`

And only the new photos added to the album were exported which is what I think you're asking for.

However, with `--only-new`, osxphotos will only evaluate photos that have not been previously exported.  osxphotos stores the IDs of each photo in an export database called `.osxphotos_export.db` in the export folder (` /Desktop/ExportPhotos/.osxphotos_export.db` in your case) Is it possible you exported photos with a different osxphotos export command to the same folder in the past?  If so, the same export database would be used and osxphotos would see those photos had previously been exported (even if they'd been added to the album since then) and wouldn't export them.  

The use case for `--only-new` is for a workflow where you want to use `--update` but you remove the photos from the export directory between runs of osxphotos. This prevents osxphotos from thinking the previously exported photos are missing and only processed previously unexported photos. 

I think for your use case, you can just use `--update`.  If you had not previously exported to the same directory and you're not seeing the expected behavior, it could be a bug but I've not been able to replicate it in the testing I did just now.  What behavior are you actually seeing?

**Comment by Rott-Apple** [comment]
Hi, thanks for the super quick reply. My colleague did the export. I will forward your reply to him and get back to you on Monday.

**Comment by Rott-Apple** [comment]
On using --update, it works correctly. Many thanks! Will look through .osxphotos_export.db to understand where you store date and time of adding/removing photos in specific albums, because Photos.sqlite (and Photos.db in Mojave and earlier) don't seem to keep this information.

**Comment by RhetTbull** [comment]
I don't think date added to the album is stored but what is stored is a sort order.  If you add new photos to an album, they're added to the end of the album (but you can manually re-order them).  There's additional details in the [wiki](https://github.com/RhetTbull/osxphotos/wiki/Photos-version-5-database#albums).  What osxphotos does when you use --album and --update is first find all the photos in the album then it looks in .osxphotos_export.db to see which of these have not previously been exported and export those.  (This information is stored in the `files` table of the export db)
