### ISSUE TITLE
`--directory` template functions convert `/` to `:`

### ISSUE THREAD

**Issue by neilpa** [RhetTbull/osxphotos#471]
I'm trying to use a template function to construct the full path to a directory but noticed that `/` are converted to `:`. I recall seeing an issue where `/` need to be converted for single path element names to make them valid but for the `--directory` option that behavior should be skipped.

**Comment by RhetTbull** [comment]
Got a test case working for this scenario so will now work on a fix.  Good catch & it should be an easy fix.

**Comment by RhetTbull** [comment]
I think this is fixed in [v0.42.36](https://github.com/RhetTbull/osxphotos/releases/tag/v0.42.36).  Let me know if you still have issues.  

Normally, all templates for --filename and --directory are sanitized to ensure they're valid path parts.  For --directory, this involved replacing any "/" with ":" as this could have unintended effects if user was using a template field that contained an embedded "/" in the value.  But with the template function, the user should have full control over this so you can create subdirectories if desired.

**Comment by neilpa** [comment]
Works great, and as always much appreciated with the super quick turnaround
