### ISSUE TITLE
--cleanup function will not recursively delete empty folders 

### ISSUE THREAD

**Issue by RhetTbull** [RhetTbull/osxphotos#491]
>The --cleanup function will not recursively delete empty folders and will only delete the lowest level empty directory on each iteration of the export command. For example, if folder Library/2021/06/21 has 1 photo that gets deleted, only the folder 21 will be deleted on the first run of the command. If you run the same command again, it will delete 06, and then run again to delete 2021 (assuming all these folders are empty after you delete the one image). This can be mitigated by running a separate python function to recursively delete any empty directories after the export command is run.

I'll open a new issue for this as I think the "expected" behavior for --cleanup should be to delete all directory trees that contain only empty directories.

_Originally posted by @RhetTbull in https://github.com/RhetTbull/osxphotos/issues/487#issuecomment-875138178_

**Comment by mkirkland4874** [comment]
Would be nice if --cleanup had the option to recursively delete all of the .DS_Store files that MacOS pollutes into the directory tree if you browse with Finder. It's easy enough to run the following after running export but would be nice if cleanup did that in order to maintain a clean synced copy. Happy to create a new issue if you think that is within the scope of osxphotos.

`find /path/to/export -name .DS_Store -type f -delete`

**Comment by RhetTbull** [comment]
> EDIT: Actually I think cleanup already does this.

Yes, cleanup will delete the .DS_Store files and any other file that wasn't included in the export set.  The only exception is the `.osxphotos_export.db` file that osxphotos uses to preserve state information between exports.

**Comment by RhetTbull** [comment]
I think this is fixed in [v0.42.60](https://github.com/RhetTbull/osxphotos/releases/tag/v0.42.60)
