### ISSUE TITLE
errors with --exiftool

### ISSUE THREAD

**Issue by avandeputte** [RhetTbull/osxphotos#494]
If I specify --exiftool,  I get a lot of errors such as these.   These files then don't get exported.
Everything works fine if I remove --exiftool in the command below.

```
alex@iMac ~ % osxphotos export /Volumes/samsung/OSXPhotos --directory "{created.year}{created.month}" --skip-original-if-edited  --download-missing --use-photokit  --exiftool  --sidecar XMP  --report export.csv
Using last opened Photos library: /Users/alex/Pictures/Photos Library.photoslibrary
Exporting 20669 photos to /Volumes/samsung/OSXPhotos...
  [------------------------------------]    0%exiftool error for file /Volumes/samsung/OSXPhotos/2019June/P6090479.jpeg: Error: [minor] Bad format (0) for CameraSettingsIFD entry 0 - /Volumes/samsung/OSXPhotos/2019June/P6090479.jpeg
Error exporting photo (024E6B7E-CDB5-4F8C-88CC-56B26F2C1298: P6090479.JPG) as /Volumes/samsung/OSXPhotos/2019June/P6090479.jpeg: Error: [minor] Bad format (0) for CameraSettingsIFD entry 0 - /Volumes/samsung/OSXPhotos/2019June/P6090479.jpeg
  [------------------------------------]    0%  04:02:49exiftool error for file /Volumes/samsung/OSXPhotos/2010March/P3290259.jpeg: Error: [minor] CameraSettingsIFD tag 0x0000 IFD format not handled - /Volumes/samsung/OSXPhotos/2010March/P3290259.jpeg
Error exporting photo (1E90AEFC-AB86-42E5-BEDB-8AA84665F37F: P3290259.JPG) as /Volumes/samsung/OSXPhotos/2010March/P3290259.jpeg: Error: [minor] CameraSettingsIFD tag 0x0000 IFD format not handled - /Volumes/samsung/OSXPhotos/2010March/P3290259.jpeg
```

**Comment by RhetTbull** [comment]
It appears these are generated by errors in the original files that exiftool is complaining about though it's possible osxphotos is generating bad options fo exiftool. Do you have one of these images you're willing to share? If you send it to Rturnbull+git@gmail.com I'll take a look at it.

You can silence the minor exiftool errors by passing exiftool the -m fag (ignore minor errors) using   `--exiftool-option '-m' `

**Comment by avandeputte** [comment]
Sent.  Thanks for taking a look,  I appreciate it.

**Comment by avandeputte** [comment]
I spoke too soon...  It's not going through,  probably because its's a 10MB file.     Anything I can run to extract what you might be looking for?

**Comment by RhetTbull** [comment]
@avandeputte I got the file -- thanks.  Looks like errors in the file that exiftool doesn't understand.  However, as exiftool sees these as "minor" errors, exiftool ignores these and I believe osxphotos and exiftool will correctly apply the metadata upon export.  In fact, I did a test of this, importing your sample image to a test library then exporting with osxphotos and exiftool did correctly apply all the metadata to the file.  You can add `--exiftool-option "-m"` to the osxphotos command line to suppress these minor errors.

Running the following exiftool command shows all the errors:

`exiftool -validate -warning -error -a file.jpeg`

```
Validate                        : 8 Warnings (7 minor)
Warning                         : [minor] Bad format (0) for CameraSettingsIFD entry 0
Warning                         : [minor] Bad RawDevelopmentIFD directory
Warning                         : [minor] Bad ImageProcessingIFD directory
Warning                         : [minor] Bad FocusInfoIFD directory
Warning                         : Non-standard format (int32u) for ExifIFD 0xa401 CustomRendered
Warning                         : [minor] Boolean value for XMP-exif:FlashFired should be capitalized
Warning                         : [minor] Boolean value for XMP-exif:FlashFunction should be capitalized
Warning                         : [minor] Boolean value for XMP-exif:FlashRedEyeMode should be capitalized
```

These could be genuine errors in the file or they could mean the file is using metadata that exiftool doesn't understand. (I used the latest version of exiftool, version 12.29).  In my experience with exiftool, it's more likely that some application has added metadata in a format that doesn't comply with the specification.  According to the `XMP:CreatorTool` tag, the image was edited with `Elements Organizer 18.0` so that might be the culprit.

**Comment by avandeputte** [comment]
Thank you.  I will add the exiftool -m option and see if there is any problems.   I will close this issue.
