### ISSUE TITLE
Repair missing Folder Structure in broken Apple Photos DB

### ISSUE THREAD

**Issue by jotzet79** [RhetTbull/osxphotos#502]
Dear @RhetTbull & developers,

Recently I had to switch off "iCloud Photo Library" on my iPad (as suggested by Apple Support to fix issues with face detection). After that I (manually) wiped all pictures from the iPad, in order to be able to start with a clean, empty lib that I could then sync again. Unfortunately I had to clean not only Pictures, but also the remainders / stubs of then empty Folders and Albums, because they were not deleted automatically. 

So far so good...  After this procedure I switched my iPad on and off, to assert that they are no left overs / hanging processes. Then I started the sync again by switching iCloud Photo Library ON again.

Next day -> nightmare: On all synced devices / Web iCloud.com all folders and sub-folders, as well as the albums were gone. 32000 pictures without anymore folder/album structure(s). 

Wait, no - obviously when SEARCHING (no matter which device) for an album name, I can find this specific Album as search result (and the pictures within). But the Album/Folder does not appear in the left panel (Mac; or the Albums section on iDevices) anymore.

That's why I tried out osxphotos's REPL mode:
`for album in photosdb.album_info: print(album.uuid, album.title, album.folder_names)`

400+ Results - yeah
`2069CFFD-B1B1-4E7C-A3EC-442DE1F05DE8 2008-01 - Berlin ['1111 - Various', '1111 - Staging', 'Events', '2008', '2008-01 - Berlin']
`

But
`for folder in photosdb.folder_info: print(folder.uuid, folder.title)`

Does NOT return the complete Folder Hierarchy anymore, although the Album from above  DOES return a folder info '/1111 - Various/1111 - Staging/Events/2008/2008-01 - Berlin'.

My plan then was to recreate either the missing folder structure, or recreate album with the same name, and  copy pictures to the newly created album, and wiping the old one.: I wanted to iterate those Album UUIDs using RhetTbull's PhotoScript Python lib, eg. by trying to select one pic in this mystic container:

```
selected = photoslib.selection
for i in selected:
    print(i.uuid)
    print(i.name)
    print(len(i.albums))

print(photoslib.album("2069CFFD-B1B1-4E7C-A3EC-442DE1F05DE8"))
```

Output:

```
A6134D7A-4AEF-4DF8-9622-A9E2437A135A

0
None
```

Is there some option to recreate the folder structure manually somehow / hack the sqlite DBs? 

THANKS for any pointers,
Jo

PS: Of course I contacted Apple Support, but no real help here
PPS: Apparently I'm not alone -> https://discussions.apple.com/thread/251172018 / https://discussions.apple.com/thread/8303360

**Comment by RhetTbull** [comment]
@jotzet79 sorry to hear of this unfortunate situation!  I do not recommend hacking on the sqlite DB itself as the schema is quite complex.  The first thing I recommend you do is backup the entire .photoslibrary folder immediately.  It seems some of the data is still in the DB so make a backup so that osxphotos can access this data even if Apple does something to it.

Then you can write a script using both photoscript and osxphotos to do what you want.  Use osxphotos to walk through each album, get the album.folder_names, then go through each folder and create a folder using photoscript's PhotosLibrary().create_folder() then create the album in the folder using photoscript's PhotosLibrary().create_album(). See the photoscript [docs](https://raw.githubusercontent.com/RhetTbull/PhotoScript/master/docs/photoscript.pdf) for reference.
 Then add the photo to the album using photoscript.

I think that by using both osxphotos to read the info that's still there and photoscript to recreate the folder structure you'll be able to fix this.  BUT make a backup first!

If you get stuck on any of the code, let me know and I'll be glad to take a look.  Good luck!
